### PR TITLE
Us1   create homepage

### PR DESCRIPTION
**Pull request by Luke-Easton**

### CODE REVIEW

**Comment by ALuffy87** [comment]
LGTM, however maybe have Jess and Alex also check before merging

**Comment by Jessica-Ball** [comment]
LGTM -  Checked it yesterday, but forgotten to comment on it :+1: It looks good to me :)

**Comment by Luke-Easton** [comment]
Once alex is happy with it, it can be signed off :)

**Comment by apirie8** [comment]
Cool! Looks good.

**Comment by apirie8** [comment]
Didn't delete branch, can revert in possible.

**Pull request merged**
