### PR TITLE
Python Page 

### PR DESCRIPTION
**Pull request by Jessica-Ball**
Finished the Python pages and ready to merge to the master branch once everyone is happy with it :) 

It can't automatically merge because of the homepage, but I will see if I can find ways around it.

### CODE REVIEW

**Comment by Luke-Easton** [comment]
Conflicting with Homepage.html

**Comment by Jessica-Ball** [comment]
Once Anna's pages are merged to the master branch, then I will change the Homepage.html file in master branch to match what it is on the Python branch.

**Comment by Luke-Easton** [comment]
LGTM :+1:

**Comment by Jessica-Ball** [comment]
Talked about the pages in the standup and everyone is happy with it to merge.

**Pull request merged**
